Data leak tests integration
DaniSchechter/Protobuf-Stripper pull request #15
Opened 2019-06-01 14:30 UTC by alonblecher

2019-06-01 15:05 UTC, alex-schechter requested changes

2019-06-01 15:05 UTC, alex-schechter commented on src/FileChecks.cpp
> +bool find_str_in_file(const std::string& fileName, const std::string& word)
change to find_word_in_file

2019-06-01 15:05 UTC, alex-schechter commented on src/FileChecks.cpp
> +		std::cout << "Unable to open the file." << std::endl;
Unable to open what file? add the name of the file. also, use our Logger instead of std::cout.

2019-06-01 15:05 UTC, alex-schechter commented on src/FileChecks.cpp
> +		while (std::getline(words, word, ',')) {
add comments everywhere

2019-06-01 15:05 UTC, alex-schechter commented on src/FileChecks.hpp
> +bool read_csv_ip_blacklist(const std::string& fileName, const std::string& IP);
if U are using _ in function names, don't write fileName, write file_name.

2019-06-01 15:05 UTC, alex-schechter commented on src/IPblackList.cpp
> +//Checks how much requests there sent to the destination Ip from different source Ips, if its the first time this ip is accessed, verify it's a legitimate site Ip by scanning the csv file for this IP
break this comment into multiple lines

2019-06-01 15:05 UTC, alex-schechter commented on src/IPblackList.cpp
> +#include"LoadSetFromFile.hpp"
put a space after the include

2019-06-01 15:05 UTC, alex-schechter commented on src/IsEncryptedRawData.cpp
> +bool Is_Encrypted(const std::string& rawdata)
is_encrypted, not Is_Encrypted.

2019-06-01 15:05 UTC, alex-schechter commented on src/LoadSetFromFile.hpp
> +
remove blank lines

2019-06-01 15:05 UTC, alex-schechter commented on src/LoadSetFromFile.hpp
> +private:
remove the private. the default of class is private

2019-06-01 15:05 UTC, alex-schechter commented on src/LoadSetFromFile.hpp
> +		//if (fileName == test_config("IP_BLACKLIST_CSV"))
remove

2019-06-01 15:05 UTC, alex-schechter commented on src/LoadSetFromFile.hpp
> +		//else
remove

2019-06-01 15:05 UTC, alex-schechter commented on src/LoadSetFromFile.hpp
> +		//if (fileName == test_config("IP_BLACKLIST_CSV"))
remove the code from all hpp files!!

2019-06-01 15:05 UTC, alex-schechter commented on src/LoadSetFromFile.hpp
> +			std::cout << "Unable to open the file." << std::endl;
print the name of the file and use the Logger

2019-06-01 15:05 UTC, alex-schechter commented on src/TestsConfig.cpp
> +	std::ifstream cFile("include/config.txt");
put in conf file

2019-06-01 15:05 UTC, alex-schechter commented on src/TestsConfig.cpp
> +			// line.erase(std::remove_if(line.begin(), line.end(), isspace),
remove

2019-06-01 15:05 UTC, alex-schechter commented on src/TestsConfig.cpp
> +			// 	line.end());
remove

2019-06-01 15:05 UTC, alex-schechter commented on src/TestsConfig.cpp
> +			auto Pos = line.find("=");
Y auto?????

2019-06-01 15:05 UTC, alex-schechter commented on src/TestsConfig.cpp
> +			auto name = line.substr(0, Pos);
std::string not auto

2019-06-01 15:05 UTC, alex-schechter commented on src/TestsConfig.cpp
> +			auto Pos = line.find("=");
Y camel case?

2019-06-01 15:05 UTC, alex-schechter commented on src/checkPacket.cpp
> +bool isForbidden(const std::string& srcIP, const std::string& dstIP, const std::string& srcPort, const std::string& dstPort, const std::string& data)
not isForbidden, is_forbidden

2019-06-01 15:05 UTC, alex-schechter commented on src/bridge.cpp
> +
this is the old code!!!!!!!

2019-06-01 15:05 UTC, alex-schechter commented on src/confidentialDataRule.cpp
> +	if (((double)countBadWords / countTotalWords) >= freq_bad_words)
return (((double)countBadWords / countTotalWords) >= freq_bad_words)

2019-06-01 15:05 UTC, alex-schechter commented on src/confientialDataRule.hpp
> +
Y so many blank lines

2019-06-01 15:05 UTC, alex-schechter commented on src/filesHandler.cpp
> +
remove blank lines

2019-06-01 15:05 UTC, alex-schechter commented on src/intervalRule.cpp
> +bool isInterval(const std::string& srcIP, const std::string& dstIP)
remove this function

2019-06-01 15:05 UTC, alex-schechter commented on src/secureBridge.hpp
> +template <class Bridge>
Y is it here?

2019-06-05 18:28 UTC, alex-schechter requested changes

2019-06-05 18:28 UTC, alex-schechter commented on include/maliciousIps.csv
> +192.229.220.226
is it sport5?

2019-06-05 18:28 UTC, alex-schechter commented on src/FileChecks.cpp
> +		Logger::log( "OPEN_FILE_ERROR, unable to open file " + file_name, Logger::LOG_LEVEL::FATAL);
Y fatal? make it a warning

2019-06-05 18:28 UTC, alex-schechter commented on src/FileChecks.cpp
> +bool read_csv_ip_blacklist(const std::string& file_name, const std::string& IP)
Y camel case? change it to ip

2019-06-05 18:28 UTC, alex-schechter commented on src/IPblackList.cpp
> +bool request_density(const std::string& srcIP, const std::string& dstIP, const std::string& rawdata) {
src_ip and so on

2019-06-05 18:28 UTC, alex-schechter commented on src/LoadSetFromFile.hpp
> +public:
Y is it here??

2019-06-05 18:28 UTC, alex-schechter commented on src/LoadSetFromFile.hpp
> +				Logger::log( "OPEN_FILE_ERROR, unable to open file " + test_config("IP_BLACKLIST_CSV"), Logger::LOG_LEVEL::FATAL);
change to warning

2019-06-05 18:28 UTC, alex-schechter commented on src/LoadSetFromFile.hpp
> +		if (!file.is_open())
you have the same code 3 times. put it in a function

2019-06-05 18:28 UTC, alex-schechter commented on src/LoadSetFromFile.hpp
> +	std::set<std::string>* get_value(const std::string& Name)
name not Name

2019-06-05 18:28 UTC, alex-schechter commented on src/bridge.cpp
> +            break;
return not break. you dont want it to print the last line

2019-06-10 23:06 UTC, DaniSchechter approved these changes

2019-06-10 23:07 UTC, merged